language: node_js
node_js:
  - 13
env:
  - CI=true
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn install
script:
  - eleventy
deploy:
  provider: script
  script: netlify deploy -p -s $NETLIFY_SITE_ID -a $NETLIFY_ACCESS_TOKEN -d ./dist
  skip_cleanup: true
  on:
    branch: master
